export const projects = [
    {
        num: "01",
        category: "frontend",
        title: "Cookie  clicker game",
        description: `In this simple cookie clicker game, you start by clicking on a cookie to earn points. With the points you accumulate, you can purchase various features to enhance your experience. These features include changing the cookie image, increasing the number of points you earn with each click, making the cookie spin, and altering the background color to customize the game's appearance. Each upgrade offers a unique way to interact with and enjoy the game, making every click more rewarding and visually appealing.`,
        stack: [{ name: "Html 5" }, { name: "Css 3" }, { name: "Javascript" }],
        image: "/assets/projectsImages/cookie-clicker.png",
        live: "https://inga911.github.io/cookie-clicker/",
        github: "https://github.com/inga911/cookie-clicker",
    },
    {
        num: "02",
        category: "frontend",
        title: "Memory cards game",
        description: `A simple memory card game where players must find matching pairs of cards before revealing all the cards. The game tracks the number of clicks a player makes and the total time taken to open all the cards. At the start of each new game, players can enter their name . The interface shows a grid of facedown cards that flip to reveal images when clicked. When a match is found, the cards remain face-up. If the cards do not match, they flip back over after a brief pause, allowing the player to remember their positions. The game includes a scoreboard displaying the current player's clicks and time, alongside a leaderboard of previous players' results, providing a competitive.`,
        stack: [{ name: "Html 5" }, { name: "Css 3" }, { name: "Javascript" }],
        image: "/assets/projectsImages/memoy-cards.png",
        live: "https://inga911.github.io/memory-cards-game/",
        github: "https://github.com/inga911/memory-cards-game",
    },
    {
        num: "03",
        category: "frontend",
        title: "Arena fight game",
        description:
            'A simple Arena fighting game built with vanilla JavaScript and CSS. Players start by choosing their character. In the game, pressing the "Attack" button grants a random amount of gold and inflicts damage on the enemy. When players accumulate 50 or more gold, they can purchase a potion to fully heal themselves. Players also have the option to choose a weapon: a sword, bow, or wand. After each game, all progress and choices reset, allowing for a fresh start.',
        stack: [{ name: "Html 5" }, { name: "Css 3" }, { name: "Javascript" }],
        image: "/assets/projectsImages/arena-fight.png",
        live: "https://inga911.github.io/arena-fight-game/",
        github: "https://github.com/inga911/arena-fight-game",
    },
    {
        num: "04",
        category: "frontend",
        title: "Weather App API",
        description:
            "A simple React.js weather app utilizes the OpenWeatherMap.org API to provide real-time weather information for various locations. Users can input a city name to retrieve current weather data, including temperature, humidity, wind speed, and weather conditions. The app features a clean and intuitive interface with a search bar for city input, and displays the retrieved weather data prominently. The app also handles error responses gracefully, providing feedback when the city is not found. Fully responsive design.",
        stack: [{ name: "Html 5" }, { name: "Css 3" }, { name: "Javascript" }],
        image: "/assets/projectsImages/weather-app-react.png",
        live: "https://inga911.github.io/weather-app-react/",
        github: "https://github.com/inga911/weather-app-react",
    },
    {
        num: "05",
        category: "frontend",
        title: "Infinite scroll API",
        description:
            "A simple web design technique using an images API, infinite scroll dynamically loads and displays images as the user scrolls down the page.",
        stack: [{ name: "Html 5" }, { name: "Css 3" }, { name: "Javascript" }],
        image: "/assets/projectsImages/infinite-scroll.png",
        live: "https://inga911.github.io/infinite-scroll/",
        github: "https://github.com/inga911/infinite-scroll",
    },
    {
        num: "06",
        category: "frontend",
        title: "Random colors",
        description:
            "A simple web design technique using an images API, infinite scroll dynamically loads and displays images as the user scrolls down the page.",
        stack: [{ name: "Html 5" }, { name: "Css 3" }, { name: "Javascript" }],
        image: "/assets/projectsImages/random-color.png",
        live: "https://inga911.github.io/random-color/",
        github: "https://github.com/inga911/random-color",
    },
    {
        num: "07",
        category: "frontend",
        title: "QR code generator",
        description:
            "Simple QR Code Generator is a handy tool that lets you create custom QR codes effortlessly. You can enter a URL and choose size and the generator will instantly generate a QR code. Once generated, you will be able to download the QR code.",
        stack: [{ name: "Html 5" }, { name: "Css 3" }, { name: "Javascript" }],
        image: "/assets/projectsImages/qr-code-generator.png",
        live: "https://inga911.github.io/qr-code-generator/",
        github: "https://github.com/inga911/qr-code-generator",
    },
    {
        num: "08",
        category: "frontend",
        title: "Calculator",
        description: "A simple calculator built with vanilla javascript and css.",
        stack: [{ name: "Html 5" }, { name: "Css 3" }, { name: "Javascript" }],
        image: "/assets/projectsImages/js-calculator.png",
        live: "https://inga911.github.io/calculator-vanilla-js/",
        github: "https://github.com/inga911/calculator-vanilla-js",
    },
];